### PR TITLE
Switch to github import path for uuid and to maintained QR Code library

### PR DESCRIPTION
**Pull request by steko**
Since the project was migrated from Google Code to GitHub, I think it makes sense to switch.

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks!

**Comment by steko** [comment]
You're welcome, this tool perfectly fits my use case so it only seems appropriate to keep it in a healthy state.

Are you going to release a new version?

**Comment by sawanoboly** [comment]
Because the function does not change, I think that there is no need to make a release.

And, the release which tagged `master` is always newest. https://github.com/giraffi/go-uuid-qrcode/releases/tag/master by travis.ci.

But after all, I've tagged and release as v0.2.0 a little while ago.

https://github.com/giraffi/go-uuid-qrcode/releases/tag/v0.2.0

Please check it.

**Comment by steko** [comment]
I agree with you that since the function remained the same it was unnecessary to release a new version.

However I think the `master` tag you're referring to could have some problems. First of all looking at the link https://github.com/giraffi/go-uuid-qrcode/releases/tag/master I see

>  sawanoboly released this on 20 Sep 2015 · 9 commits to master since this release 

and that's because you have a `master` **tag** pointing to a specific commit, that is different from the master **branch**. This also causes problems for `git push` (I had to delete the tag myself in order to push to my fork):

```
➜  go-uuid-qrcode git:(master) git push origin master 
error: src refspec master matches more than one.
error: failed to push some refs to 'git@github.com:giraffi/go-uuid-qrcode.git'
```

I'm not sure my explanation makes sense but I hope it is helpful. Thank you!

**Comment by sawanoboly** [comment]
Whoops... I used $TRAVIS_BRANCH to tag to automatically releasing. I have to repair my repo.

**Pull request merged**
